Handling chr header
Multiscale-Genomics/C-HiC pull request #4
Opened 2018-08-20 10:08 UTC by pabloacera

This branch maintain and handles the chromosome name of the input files.

2018-08-21 13:29 UTC, markmcdowall requested changes
Could you check the pylint reviews and fix the issues that they have raised.

Is the bam2chicago.sh script the one that we were talking about earlier?

2018-08-21 13:29 UTC, markmcdowall commented on CHiC/tool/makeBaitmap.py
> +                chr_dict[int(line_hdl[0])] = line_hdl[1]
Unless this is a file that you have created separately you can't always guarantee that this will always be an integer (eg the MT chromosome).

2018-08-24 13:44 UTC, pabloacera commented on CHiC/tool/makeBaitmap.py
> +                chr_dict[int(line_hdl[0])] = line_hdl[1]
Yes, so chr_handler is a file that I am creating in the previous tool rmap_tool.py, which scan the reference genome and creates dummy chromosomes (1,2,3,4...) and then it matches with the real chromosome name written in the reference genome. So in this case line_hdl[0] contains the dummy chromosomes (which are always numbers) and line_hdl[1] which are the real chromosome names. Does it makes sense?

2018-09-06 12:27 UTC, markmcdowall commented
Were you able to have a look t resolving the errors that are highlighted on Travis?

Also you should remove the file C_HiC.egg-info/PKG-INFO and make sure that the C_HiC.egg-info dir is never added to the repo. This is automatically generated by pip.

2018-09-25 14:44 UTC, merged